# Generated by Django 6.1.1 on 2026-09-04 01:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('cnpj', models.CharField(help_text='Somente os 14 dígitos.', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Informe o CNPJ com exatamente 14 dígitos.', regex='^\\d{14}$')], verbose_name='CNPJ')),
                ('divergence_tolerance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='tolerância de divergência em reais')),
                ('divergence_tolerance_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Fração decimal entre 0 e 1; por exemplo, 0,02 representa 2%.', max_digits=7, verbose_name='tolerância percentual')),
                ('duplicate_window_days', models.PositiveSmallIntegerField(default=30, verbose_name='janela de duplicidade em dias')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('cnpj__regex', '^\\d{14}$')), name='tenants_cnpj_has_14_digits'), models.CheckConstraint(condition=models.Q(('divergence_tolerance_amount__gte', 0)), name='tenants_tolerance_amount_non_negative'), models.CheckConstraint(condition=models.Q(('divergence_tolerance_percentage__gte', 0), ('divergence_tolerance_percentage__lte', 1)), name='tenants_tolerance_percentage_between_0_and_1'), models.CheckConstraint(condition=models.Q(('duplicate_window_days__gte', 1)), name='tenants_duplicate_window_days_positive')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], db_index=True, default='viewer', max_length=16, verbose_name='papel')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'vínculo',
                'verbose_name_plural': 'vínculos',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'role', 'is_active'], name='tenants_membership_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='tenants_membership_tenant_user_unique'), models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'operator', 'viewer'])), name='tenants_membership_role_valid')],
            },
        ),
    ]
