# Generated by Django 6.1.1 on 2026-09-04 17:38

import django.core.validators
import django.db.models.deletion
import smartaudit.documents.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255, verbose_name='nome original')),
                ('document_type', models.CharField(choices=[('unknown', 'Não identificado'), ('cte', 'CT-e'), ('nfe', 'NF-e')], db_index=True, default='unknown', max_length=16, verbose_name='tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('processed', 'Processado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('content_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')], verbose_name='SHA-256')),
                ('access_key', models.CharField(blank=True, max_length=44, validators=[django.core.validators.RegexValidator('^\\d{44}$')], verbose_name='chave de acesso')),
                ('source_file', models.FileField(blank=True, max_length=500, upload_to=smartaudit.documents.models.document_upload_path, verbose_name='XML original')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='código do erro')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'upload de documento',
                'verbose_name_plural': 'uploads de documentos',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key', models.CharField(max_length=44, validators=[django.core.validators.RegexValidator('^\\d{44}$')], verbose_name='chave de acesso')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('series', models.CharField(max_length=10, verbose_name='série')),
                ('issue_at', models.DateTimeField(verbose_name='emitido em')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('complementary', 'Complementar'), ('annulment', 'Anulação'), ('substitute', 'Substituição')], default='normal', max_length=20, verbose_name='status')),
                ('sender_cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$')], verbose_name='CNPJ do remetente')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='remetente')),
                ('sender_state', models.CharField(blank=True, max_length=2, verbose_name='UF do remetente')),
                ('sender_zip', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')], verbose_name='CEP do remetente')),
                ('recipient_cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$')], verbose_name='CNPJ do destinatário')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='destinatário')),
                ('recipient_state', models.CharField(blank=True, max_length=2, verbose_name='UF do destinatário')),
                ('recipient_zip', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')], verbose_name='CEP do destinatário')),
                ('carrier_cnpj', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$')], verbose_name='CNPJ da transportadora')),
                ('carrier_name', models.CharField(max_length=255, verbose_name='transportadora')),
                ('total_freight', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='frete total')),
                ('cargo_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='valor da carga')),
                ('freight_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='peso da carga')),
                ('referenced_nfe_keys', models.JSONField(default=list, verbose_name='chaves de NF-e referenciadas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cte', to='documents.documentupload')),
            ],
            options={
                'verbose_name': 'CT-e',
                'verbose_name_plural': 'CT-es',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key', models.CharField(max_length=44, validators=[django.core.validators.RegexValidator('^\\d{44}$')], verbose_name='chave de acesso')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('series', models.CharField(max_length=10, verbose_name='série')),
                ('issue_at', models.DateTimeField(verbose_name='emitida em')),
                ('issuer_cnpj', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$')], verbose_name='CNPJ do emitente')),
                ('issuer_name', models.CharField(max_length=255, verbose_name='emitente')),
                ('recipient_cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$')], verbose_name='CNPJ do destinatário')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='destinatário')),
                ('recipient_zip', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')], verbose_name='CEP do destinatário')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor total')),
                ('gross_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='peso bruto')),
                ('net_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='peso líquido')),
                ('total_volume', models.PositiveIntegerField(default=0, verbose_name='volumes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nfe', to='documents.documentupload')),
            ],
            options={
                'verbose_name': 'NF-e',
                'verbose_name_plural': 'NF-es',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CTeNFeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_links', to='documents.cte')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cte_links', to='documents.nfe')),
            ],
            options={
                'verbose_name': 'vínculo CT-e/NF-e',
                'verbose_name_plural': 'vínculos CT-e/NF-e',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='documentupload',
            constraint=models.UniqueConstraint(fields=('tenant', 'content_sha256'), name='documents_upload_tenant_hash_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentupload',
            constraint=models.UniqueConstraint(condition=models.Q(('access_key', ''), _negated=True), fields=('tenant', 'document_type', 'access_key'), name='documents_upload_tenant_type_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentupload',
            constraint=models.CheckConstraint(condition=models.Q(('content_sha256__regex', '^[0-9a-f]{64}$')), name='documents_upload_sha256_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentupload',
            constraint=models.CheckConstraint(condition=models.Q(('access_key', ''), ('access_key__regex', '^\\d{44}$'), _connector='OR'), name='documents_upload_access_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentupload',
            constraint=models.CheckConstraint(condition=models.Q(('document_type__in', ('unknown', 'cte', 'nfe'))), name='documents_upload_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentupload',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'processing', 'processed', 'failed'))), name='documents_upload_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.UniqueConstraint(fields=('tenant', 'access_key'), name='documents_cte_tenant_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.CheckConstraint(condition=models.Q(('access_key__regex', '^\\d{44}$')), name='documents_cte_access_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.CheckConstraint(condition=models.Q(('total_freight__gte', 0)), name='documents_cte_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.CheckConstraint(condition=models.Q(('cargo_value__gte', 0)), name='documents_cte_cargo_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.CheckConstraint(condition=models.Q(('freight_weight__gte', 0)), name='documents_cte_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('normal', 'complementary', 'annulment', 'substitute'))), name='documents_cte_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sender_cnpj', ''), ('sender_cnpj__regex', '^\\d{14}$'), _connector='OR'), models.Q(('recipient_cnpj', ''), ('recipient_cnpj__regex', '^\\d{14}$'), _connector='OR'), ('carrier_cnpj__regex', '^\\d{14}$')), name='documents_cte_cnpj_normalized'),
        ),
        migrations.AddConstraint(
            model_name='cte',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sender_zip', ''), ('sender_zip__regex', '^\\d{8}$'), _connector='OR'), models.Q(('recipient_zip', ''), ('recipient_zip__regex', '^\\d{8}$'), _connector='OR')), name='documents_cte_zip_normalized'),
        ),
        migrations.AddConstraint(
            model_name='nfe',
            constraint=models.UniqueConstraint(fields=('tenant', 'access_key'), name='documents_nfe_tenant_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='nfe',
            constraint=models.CheckConstraint(condition=models.Q(('access_key__regex', '^\\d{44}$')), name='documents_nfe_access_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='nfe',
            constraint=models.CheckConstraint(condition=models.Q(('total_value__gte', 0)), name='documents_nfe_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='nfe',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight__gte', 0), ('net_weight__gte', 0)), name='documents_nfe_weights_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='nfe',
            constraint=models.CheckConstraint(condition=models.Q(('issuer_cnpj__regex', '^\\d{14}$'), models.Q(('recipient_cnpj', ''), ('recipient_cnpj__regex', '^\\d{14}$'), _connector='OR')), name='documents_nfe_cnpj_normalized'),
        ),
        migrations.AddConstraint(
            model_name='nfe',
            constraint=models.CheckConstraint(condition=models.Q(('recipient_zip', ''), ('recipient_zip__regex', '^\\d{8}$'), _connector='OR'), name='documents_nfe_zip_normalized'),
        ),
        migrations.AddConstraint(
            model_name='ctenfelink',
            constraint=models.UniqueConstraint(fields=('tenant', 'cte', 'nfe'), name='documents_cte_nfe_link_unique'),
        ),
    ]
